export const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    description: "A novel by Harper Lee",
    image: "https://m.media-amazon.com/images/I/81YkqyaFVEL._SY522_.jpg",
    ratings: 4.5,
    originalPrice: "$12.99",
    price: "$9.99",
    author: "Harper Lee",
  },
  {
    id: 2,
    title: "1984",
    description: "A dystopian novel by George Orwell",
    image: "https://m.media-amazon.com/images/I/81YkqyaFVEL._SY522_.jpg",
    ratings: 4.8,
    originalPrice: "$14.99",
    price: "$11.99",
    author: "George Orwell",
  },
  {
    id: 3,
    title: "The Great Gatsby",
    description: "A novel by F. Scott Fitzgerald",
    image: "https://m.media-amazon.com/images/I/81YkqyaFVEL._SY522_.jpg",
    ratings: 4.7,
    originalPrice: "$11.99",
    price: "$8.99",
    author: "F. Scott Fitzgerald",
  },
  {
    id: 4,
    title: "Moby-Dick",
    description: "A novel by Herman Melville",
    image: "https://m.media-amazon.com/images/I/81YkqyaFVEL._SY522_.jpg",
    ratings: 4.6,
    originalPrice: "$13.99",
    price: "$10.99",
    author: "Herman Melville",
  },
  {
    id: 5,
    title: "Pride and Prejudice",
    description: "A novel by Jane Austen",
    image: "https://m.media-amazon.com/images/I/81YkqyaFVEL._SY522_.jpg",
    ratings: 4.9,
    originalPrice: "$10.99",
    price: "$7.99",
    author: "Jane Austen",
  },
  {
    id: 6,
    title: "The Catcher in the Rye",
    description: "A novel by J.D. Salinger",
    image: "https://m.media-amazon.com/images/I/81YkqyaFVEL._SY522_.jpg",
    ratings: 4.5,
    originalPrice: "$9.99",
    price: "$6.99",
    author: "J.D. Salinger",
  },
];
